const localLove = [
  {
    id: 1,
    quote: "Love grows strongest in the quiet moments when no one is watching.",
    author: "Clara Bennett",
    year: 2019,
    source: "The Quiet Between Us",
    category: "Commitment",
    tags: ["love", "commitment", "relationships"],
    mood: "Hopeful",
    language: "English",
  },
  {
    id: 2,
    quote: "A heart that feels understood never forgets the one who listened.",
    author: "Elias Moore",
    year: 2021,
    source: "Letters to Tomorrow",
    category: "Romantic",
    tags: ["love", "trust", "connection"],
    mood: "Warm",
    language: "English",
  },
  {
    id: 3,
    quote:
      "The smallest acts of kindness often become the greatest declarations of love.",
    author: "Sophia Hayes",
    year: 2018,
    source: "Gentle Hearts",
    category: "Kindness",
    tags: ["kindness", "love", "life"],
    mood: "Tender",
    language: "English",
  },
  {
    id: 4,
    quote:
      "Love is not found in perfection but in choosing each other despite imperfections.",
    author: "Noah Carter",
    year: 2020,
    source: "Everyday Forever",
    category: "Acceptance",
    tags: ["acceptance", "relationships", "growth"],
    mood: "Reflective",
    language: "English",
  },
  {
    id: 5,
    quote:
      "Two people become home when they carry peace into each other's lives.",
    author: "Emma Collins",
    year: 2022,
    source: "Home in You",
    category: "Soulmates",
    tags: ["peace", "love", "home"],
    mood: "Warm",
    language: "English",
  },
  {
    id: 6,
    quote:
      "The best love stories are written through ordinary days shared together.",
    author: "Lucas Bennett",
    year: 2017,
    source: "Common Days",
    category: "Romantic",
    tags: ["life", "romance", "partnership"],
    mood: "Joyful",
    language: "English",
  },
  {
    id: 7,
    quote: "A patient heart gives love the time it needs to bloom.",
    author: "Grace Walker",
    year: 2016,
    source: "Bloom Slowly",
    category: "Patience",
    tags: ["patience", "growth", "love"],
    mood: "Hopeful",
    language: "English",
  },
  {
    id: 8,
    quote: "The strongest promises are often spoken without words.",
    author: "Oliver Reed",
    year: 2023,
    source: "Silent Vows",
    category: "Commitment",
    tags: ["promise", "trust", "love"],
    mood: "Tender",
    language: "English",
  },
  {
    id: 9,
    quote:
      "Love becomes unforgettable when it makes someone feel completely seen.",
    author: "Mia Foster",
    year: 2018,
    source: "Seen",
    category: "Connection",
    tags: ["connection", "care", "relationships"],
    mood: "Warm",
    language: "English",
  },
  {
    id: 10,
    quote:
      "Every lasting relationship is built one thoughtful choice at a time.",
    author: "Henry Brooks",
    year: 2024,
    source: "Daily Choices",
    category: "Commitment",
    tags: ["relationships", "choices", "love"],
    mood: "Hopeful",
    language: "English",
  },
];

export default localLove;
