const localLove = [
  {
    id: 1,
    quote: "Love grows strongest in the quiet moments when no one is watching.",
    author: "Clara Bennett",
    year: 2019,
    source: "The Quiet Between Us",
    category: "Commitment",
    tags: ["love", "commitment", "relationships"],
    mood: "Hopeful",
    language: "English",
  },
  {
    id: 2,
    quote: "A heart that feels understood never forgets the one who listened.",
    author: "Elias Moore",
    year: 2021,
    source: "Letters to Tomorrow",
    category: "Romantic",
    tags: ["love", "trust", "connection"],
    mood: "Warm",
    language: "English",
  },
  {
    id: 3,
    quote:
      "The smallest acts of kindness often become the greatest declarations of love.",
    author: "Sophia Hayes",
    year: 2018,
    source: "Gentle Hearts",
    category: "Kindness",
    tags: ["kindness", "love", "life"],
    mood: "Tender",
    language: "English",
  },
  {
    id: 4,
    quote:
      "Love is not found in perfection but in choosing each other despite imperfections.",
    author: "Noah Carter",
    year: 2020,
    source: "Everyday Forever",
    category: "Acceptance",
    tags: ["acceptance", "relationships", "growth"],
    mood: "Reflective",
    language: "English",
  },
  {
    id: 5,
    quote:
      "Two people become home when they carry peace into each other's lives.",
    author: "Emma Collins",
    year: 2022,
    source: "Home in You",
    category: "Soulmates",
    tags: ["peace", "love", "home"],
    mood: "Warm",
    language: "English",
  },
  {
    id: 6,
    quote:
      "The best love stories are written through ordinary days shared together.",
    author: "Lucas Bennett",
    year: 2017,
    source: "Common Days",
    category: "Romantic",
    tags: ["life", "romance", "partnership"],
    mood: "Joyful",
    language: "English",
  },
  {
    id: 7,
    quote: "A patient heart gives love the time it needs to bloom.",
    author: "Grace Walker",
    year: 2016,
    source: "Bloom Slowly",
    category: "Patience",
    tags: ["patience", "growth", "love"],
    mood: "Hopeful",
    language: "English",
  },
  {
    id: 8,
    quote: "The strongest promises are often spoken without words.",
    author: "Oliver Reed",
    year: 2023,
    source: "Silent Vows",
    category: "Commitment",
    tags: ["promise", "trust", "love"],
    mood: "Tender",
    language: "English",
  },
  {
    id: 9,
    quote:
      "Love becomes unforgettable when it makes someone feel completely seen.",
    author: "Mia Foster",
    year: 2018,
    source: "Seen",
    category: "Connection",
    tags: ["connection", "care", "relationships"],
    mood: "Warm",
    language: "English",
  },
  {
    id: 10,
    quote:
      "Every lasting relationship is built one thoughtful choice at a time.",
    author: "Henry Brooks",
    year: 2024,
    source: "Daily Choices",
    category: "Commitment",
    tags: ["relationships", "choices", "love"],
    mood: "Hopeful",
    language: "English",
  },
  {
    id: 11,
    quote:
      "Love is measured less by grand gestures and more by daily devotion.",
    author: "Amelia Stone",
    year: 2021,
    source: "Everyday Devotion",
    category: "Commitment",
    tags: ["devotion", "love", "relationships"],
    mood: "Warm",
    language: "English",
  },
  {
    id: 12,
    quote: "A shared laugh can heal wounds that words never could.",
    author: "Daniel Harper",
    year: 2019,
    source: "Hearts in Harmony",
    category: "Joy",
    tags: ["laughter", "healing", "love"],
    mood: "Joyful",
    language: "English",
  },
  {
    id: 13,
    quote:
      "The safest place in the world is beside someone who truly understands you.",
    author: "Isabella Monroe",
    year: 2020,
    source: "Safe Haven",
    category: "Connection",
    tags: ["trust", "comfort", "relationships"],
    mood: "Tender",
    language: "English",
  },
  {
    id: 14,
    quote: "Love whispers long before it ever learns to shout.",
    author: "Nathan Cole",
    year: 2017,
    source: "Whispered Promises",
    category: "Romantic",
    tags: ["romance", "feelings", "love"],
    mood: "Hopeful",
    language: "English",
  },
  {
    id: 15,
    quote: "The people who love us best remind us who we are when we forget.",
    author: "Charlotte Evans",
    year: 2022,
    source: "Remember Me",
    category: "Support",
    tags: ["support", "identity", "care"],
    mood: "Reflective",
    language: "English",
  },
  {
    id: 16,
    quote: "True love never asks for perfection, only honesty.",
    author: "Samuel Brooks",
    year: 2018,
    source: "Honest Hearts",
    category: "Trust",
    tags: ["honesty", "trust", "relationships"],
    mood: "Warm",
    language: "English",
  },
  {
    id: 17,
    quote: "Distance tests love, but commitment teaches it how to endure.",
    author: "Lily Carter",
    year: 2023,
    source: "Miles Apart",
    category: "Long Distance",
    tags: ["distance", "commitment", "love"],
    mood: "Hopeful",
    language: "English",
  },
  {
    id: 18,
    quote: "Love leaves fingerprints on every life it touches.",
    author: "Benjamin Hayes",
    year: 2016,
    source: "Lasting Impressions",
    category: "Life",
    tags: ["impact", "kindness", "love"],
    mood: "Reflective",
    language: "English",
  },
  {
    id: 19,
    quote: "Some souls meet only once, yet remain together forever in memory.",
    author: "Evelyn Brooks",
    year: 2021,
    source: "Echoes of Us",
    category: "Soulmates",
    tags: ["memory", "soulmates", "love"],
    mood: "Bittersweet",
    language: "English",
  },
  {
    id: 20,
    quote:
      "The deepest affection is often shown through the simplest acts of care.",
    author: "Julian Pierce",
    year: 2024,
    source: "Simple Things",
    category: "Kindness",
    tags: ["care", "kindness", "relationships"],
    mood: "Tender",
    language: "English",
  },
  {
    id: 21,
    quote:
      "Love is the quiet confidence that someone will still be there tomorrow.",
    author: "Abigail Turner",
    year: 2022,
    source: "Tomorrow Together",
    category: "Commitment",
    tags: ["love", "trust", "future"],
    mood: "Hopeful",
    language: "English",
  },
  {
    id: 22,
    quote: "The greatest gift we offer another is our undivided attention.",
    author: "Matthew Ellis",
    year: 2019,
    source: "Present Hearts",
    category: "Connection",
    tags: ["presence", "care", "love"],
    mood: "Warm",
    language: "English",
  },
  {
    id: 23,
    quote: "Love asks us to become softer without becoming weaker.",
    author: "Hannah Blake",
    year: 2020,
    source: "Open Hands",
    category: "Growth",
    tags: ["strength", "growth", "love"],
    mood: "Reflective",
    language: "English",
  },
  {
    id: 24,
    quote:
      "Home is not a place but the person who makes every place feel familiar.",
    author: "Caleb Morgan",
    year: 2021,
    source: "Where You Are",
    category: "Soulmates",
    tags: ["home", "comfort", "relationships"],
    mood: "Tender",
    language: "English",
  },
  {
    id: 25,
    quote:
      "A relationship grows each time two people choose understanding over pride.",
    author: "Victoria James",
    year: 2018,
    source: "Growing Together",
    category: "Acceptance",
    tags: ["understanding", "relationships", "growth"],
    mood: "Hopeful",
    language: "English",
  },
  {
    id: 26,
    quote: "The most beautiful promises are kept in everyday actions.",
    author: "Logan Pierce",
    year: 2024,
    source: "Small Promises",
    category: "Commitment",
    tags: ["actions", "love", "promise"],
    mood: "Warm",
    language: "English",
  },
  {
    id: 27,
    quote: "Love makes ordinary sunsets feel like unforgettable memories.",
    author: "Ella Montgomery",
    year: 2017,
    source: "Golden Evenings",
    category: "Romantic",
    tags: ["romance", "memories", "beauty"],
    mood: "Joyful",
    language: "English",
  },
  {
    id: 28,
    quote: "Sometimes the kindest words are simply, 'I'm here.'",
    author: "Nathaniel Ross",
    year: 2023,
    source: "Always Here",
    category: "Support",
    tags: ["support", "care", "relationships"],
    mood: "Tender",
    language: "English",
  },
  {
    id: 29,
    quote: "Love flourishes where gratitude is spoken often.",
    author: "Lillian Harper",
    year: 2022,
    source: "Grateful Hearts",
    category: "Gratitude",
    tags: ["gratitude", "love", "joy"],
    mood: "Warm",
    language: "English",
  },
  {
    id: 30,
    quote:
      "The strongest couples are those who never stop learning each other.",
    author: "Jacob Foster",
    year: 2021,
    source: "Still Discovering",
    category: "Relationships",
    tags: ["growth", "partnership", "love"],
    mood: "Hopeful",
    language: "English",
  },
  {
    id: 31,
    quote:
      "A gentle heart has the power to change another person's entire day.",
    author: "Sophie Matthews",
    year: 2019,
    source: "Gentle Days",
    category: "Kindness",
    tags: ["kindness", "heart", "love"],
    mood: "Tender",
    language: "English",
  },
  {
    id: 32,
    quote: "Love becomes extraordinary when it survives ordinary life.",
    author: "Owen Bennett",
    year: 2020,
    source: "Ordinary Forever",
    category: "Commitment",
    tags: ["everyday", "marriage", "love"],
    mood: "Reflective",
    language: "English",
  },
  {
    id: 33,
    quote: "Every sincere apology is another chance for love to grow.",
    author: "Scarlett Hughes",
    year: 2018,
    source: "Second Chances",
    category: "Forgiveness",
    tags: ["forgiveness", "growth", "relationships"],
    mood: "Hopeful",
    language: "English",
  },
  {
    id: 34,
    quote: "True affection is patient enough to wait without losing hope.",
    author: "Ryan Cooper",
    year: 2016,
    source: "Waiting Well",
    category: "Patience",
    tags: ["hope", "patience", "love"],
    mood: "Warm",
    language: "English",
  },
  {
    id: 35,
    quote: "Love leaves every heart a little brighter than it found it.",
    author: "Audrey Collins",
    year: 2024,
    source: "Brighter Days",
    category: "Life",
    tags: ["joy", "kindness", "love"],
    mood: "Joyful",
    language: "English",
  },
  {
    id: 36,
    quote: "Two people who dream together build a future worth protecting.",
    author: "Thomas Greene",
    year: 2022,
    source: "Shared Horizons",
    category: "Future",
    tags: ["dreams", "future", "relationships"],
    mood: "Hopeful",
    language: "English",
  },
  {
    id: 37,
    quote: "The language of love is spoken best through consistency.",
    author: "Claire Donovan",
    year: 2019,
    source: "Steady Hearts",
    category: "Commitment",
    tags: ["consistency", "trust", "love"],
    mood: "Reflective",
    language: "English",
  },
  {
    id: 38,
    quote:
      "Nothing strengthens a relationship like choosing grace over being right.",
    author: "Aaron Mitchell",
    year: 2023,
    source: "Grace First",
    category: "Acceptance",
    tags: ["grace", "relationships", "understanding"],
    mood: "Tender",
    language: "English",
  },
  {
    id: 39,
    quote: "The heart remembers every kindness, even the quiet ones.",
    author: "Madeline Price",
    year: 2018,
    source: "Quiet Kindness",
    category: "Kindness",
    tags: ["kindness", "memory", "love"],
    mood: "Warm",
    language: "English",
  },
  {
    id: 40,
    quote:
      "Love is strongest when both people feel safe enough to be themselves.",
    author: "Ethan Sullivan",
    year: 2021,
    source: "Safe to Stay",
    category: "Trust",
    tags: ["trust", "authenticity", "relationships"],
    mood: "Hopeful",
    language: "English",
  },
];

export default localLove;
